spring:
    # mvc:
    #     static-path-pattern:
    web:
        resources:
            add-mappings: false
            # static-locations:
            #     - classpath:/static/website/assets
    profiles:
        active: dev
    application:
        name: techstock
    # datasource:
    #     url: jdbc:h2:mem:mydb
    #     username: sa
    #     password:
    #     driverClassName: org.h2.Driver
    # jpa:
    #     database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        driver-class-name: org.postgresql.Driver
        url: "jdbc:postgresql://localhost:5432/techstock"
        username: ${DATASOURCE_USERNAME:root}
        password: ${DATASOURCE_PASSWORD:root}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
server:
    port: "8090"
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
#OpenAPI Properties
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    default-produces-media-type: application/json
    # email: example@example.org
# JWT
token:
    secret: ${JWT_SECRET}
    expiration: 604800 # token com duração de 7 dias
